// <auto-generated />
namespace AutoCadet.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VideoLessons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VideoLessons));
        
        string IMigrationMetadata.Id
        {
            get { return "201611040813050_VideoLessons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
