// <auto-generated />
namespace AutoCadet.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class instructor_price_nummable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(instructor_price_nummable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804120742207_instructor_price_nummable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
